# -*- coding: utf-8 -*-
"""News chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgPAGnIPkeaw5hmuasiPNVUJZP4fwqmw
"""

!pip install langchain langchain-community langchain-core faiss-cpu groq requests sentence-transformers

import os

os.environ["GROQ_API_KEY"] = "*******"
NEWS_API_KEY = "1b1799e66b60479dae0f8660676feed8"

import requests

def fetch_news(query: str) -> str:
    url = f"https://newsapi.org/v2/everything?q={query}&apiKey={NEWS_API_KEY}&pageSize=5"
    data = requests.get(url).json()

    articles = data.get("articles", [])
    if not articles:
        return "No news found."

    news = ""
    for i, a in enumerate(articles):
        news += f"{i+1}. {a['title']} - {a['description']}\n"

    return news

from langchain_core.tools import Tool

news_tool = Tool(
    name="News Fetcher",
    func=fetch_news,
    description="Fetch latest news based on a topic"
)

from langchain_community.chat_models import ChatOpenAI

llm = ChatOpenAI(
    model="openai/gpt-oss-120b",
    openai_api_key=os.environ["GROQ_API_KEY"],
    openai_api_base="https://api.groq.com/openai/v1"
)

from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

# Embedding model
embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# Initialize FAISS DB
vector_db = FAISS.from_texts(["Initial memory"], embedding_model)

retriever = vector_db.as_retriever(search_kwargs={"k": 3})

def retrieve_memory(query):
    docs = retriever.invoke(query)
    return "\n".join([doc.page_content for doc in docs])

def store_memory(text):
    vector_db.add_texts([text])

def chatbot(query):
    # Step 1: Get past memory
    past_context = retrieve_memory(query)

    # Step 2: Get real-time news
    news_data = fetch_news(query)

    # Step 3: Build prompt
    prompt = f"""
    You are a real-time news assistant.

    IMPORTANT:
    - Always use the provided news data
    - Never say "I don't have live data"
    - Answer ONLY from the news context
    - If question is about sports/live events, prioritize latest news

    User Question:
    {query}

    Latest News:
    {news_data}

    Answer in 5 bullet points.
    """

    # Step 4: LLM call
    response = llm.invoke(prompt)

    # Step 5: Store memory
    store_memory(f"Q: {query}\nA: {response.content}")

    return response.content

while True:
    user_input = input("Enter your Query: ")

    if user_input.lower() in ["exit", "quit"]:
        break

    answer = chatbot(user_input)
    print("Bot:", answer)